# Generated by Django 6.0.5 on 2026-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directmessages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="user1_unread_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user2_unread_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
