# Generated by Django 6.0.5 on 2026-06-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directmessages", "0002_conversation_user1_unread_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="user1_rejoin_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user2_rejoin_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
