# Generated by Django 6.0.5 on 2026-06-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_remove_comment_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentlike",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
