# Generated by Django 6.0.5 on 2026-06-02 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_remove_commentlike_updated_at_comment_updated_at"),
        ("posts", "0003_post_updated_at_postspot_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default="01JWPK7R2MNBX5QD8FHYC3VT9E",
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.post",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "user"], name="comment_post_id_e3a913_idx"
            ),
        ),
    ]
