# Generated by Django 6.0.5 on 2026-06-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_comment_post_comment_comment_post_id_e3a913_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
