# Generated by Django 6.0.5 on 2026-07-07 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_comment_like_count"),
        ("posts", "0017_bookmark_bookmarks_user_id_2ce2db_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["user", "created_at"], name="comment_user_id_779579_idx"
            ),
        ),
    ]
