# Generated by Django 6.0.5 on 2026-05-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_type",
            field=models.CharField(
                choices=[("email", "Email"), ("kakao", "Kakao"), ("google", "Google")],
                default="email",
                max_length=10,
            ),
        ),
    ]
