# Generated by Django 6.0.5 on 2026-06-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.utils.ulid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTaste",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codeword_counts", models.JSONField(default=dict)),
                ("codebook_version", models.CharField(default="v1", max_length=16)),
                ("alpha", models.FloatField(default=0.0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
