# Generated by Django 6.0.5 on 2026-06-12 04:53

import apps.core.utils.ulid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("social_id", models.CharField(max_length=255)),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("kakao", "Kakao"),
                            ("google", "Google"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "social_accounts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("login_type", "social_id"), name="unique_social_account"
                    )
                ],
            },
        ),
    ]
