# Generated by Django 6.0.5 on 2026-06-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_socialaccount"),
        ("users", "0004_usertaste"),
    ]

    operations = []
