# Generated by Django 6.0.5 on 2026-07-02 02:36

from django.db import migrations, models
from django.db.models import Count, OuterRef, Subquery


def sync_unread_count(apps, schema_editor):
    User = apps.get_model("users", "User")
    Notification = apps.get_model("notifications", "Notification")

    unread_subquery = (
        Notification.objects.filter(receiver=OuterRef("pk"), is_read=False)
        .values("receiver")
        .annotate(cnt=Count("id"))
        .values("cnt")
    )
    users = list(
        User.objects.annotate(real_count=Subquery(unread_subquery)).iterator(
            chunk_size=500
        )
    )
    for user in users:
        user.unread_noti_count = user.real_count or 0
    User.objects.bulk_update(users, ["unread_noti_count"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_merge_0004_socialaccount_0004_usertaste"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unread_noti_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(sync_unread_count, migrations.RunPython.noop),
    ]
