# Generated by Django 6.0.5 on 2026-07-02 02:36

from django.db import migrations, models
from django.db.models import Count, OuterRef, Subquery


def sync_unread_count(apps, schema_editor):
    User = apps.get_model("users", "User")
    Notification = apps.get_model("notifications", "Notification")

    unread_subquery = (
        Notification.objects.filter(receiver=OuterRef("pk"), is_read=False)
        .values("receiver")
        .annotate(cnt=Count("id"))
        .values("cnt")
    )
    qs = User.objects.annotate(real_count=Subquery(unread_subquery)).order_by("pk")
    CHUNK = 500
    offset = 0
    while True:
        chunk = list(qs[offset : offset + CHUNK])
        if not chunk:
            break
        for user in chunk:
            user.unread_noti_count = user.real_count or 0
        User.objects.bulk_update(chunk, ["unread_noti_count"], batch_size=CHUNK)
        offset += CHUNK


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_merge_0004_socialaccount_0004_usertaste"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unread_noti_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(sync_unread_count, migrations.RunPython.noop),
    ]
