# Generated by Django 6.0.5 on 2026-07-02 02:36

from django.db import migrations, models


def sync_unread_count(apps, schema_editor):
    User = apps.get_model("users", "User")
    Notification = apps.get_model("notifications", "Notification")
    for user in User.objects.all():
        user.unread_noti_count = Notification.objects.filter(
            receiver=user, is_read=False
        ).count()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_merge_0004_socialaccount_0004_usertaste"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unread_noti_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(sync_unread_count, migrations.RunPython.noop),
    ]
