# Generated by Django 6.0.5 on 2026-07-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0006_user_unread_noti_count"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("unread_noti_count__gte", 0)),
                name="unread_noti_count_non_negative",
            ),
        ),
    ]
