# Generated by Django 6.0.5 on 2026-08-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0008_user_nickname_trigram_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bookmark_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("bookmark_count__gte", 0)),
                name="bookmark_count_non_negative",
            ),
        ),
    ]
