# Generated by Django 6.0.5 on 2026-08-05 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="faqfeedback",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("faq", "user"),
                name="uniq_faq_feedback_per_user",
            ),
        ),
    ]
