# Generated by Django 6.0.5 on 2026-08-11 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supports", "0003_inquiry_inquiryanswer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                condition=models.Q(("img_key__isnull", False)),
                fields=["img_key"],
                name="ix_inquiry_img_key",
            ),
        ),
    ]
