# Generated by Django 6.0.5 on 2026-08-11 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supports", "0003_inquiry_inquiryanswer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingInquiryAttachmentDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pending_inquiry_attachment_deletions",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("img_key__isnull", False)),
                fields=("img_key",),
                name="uq_inquiry_img_key",
            ),
        ),
    ]
