# Generated by Django 6.0.5 on 2026-08-11 06:19

import logging

from django.conf import settings
from django.db import migrations, models

logger = logging.getLogger(__name__)


def _null_out_duplicate_img_keys(apps, schema_editor):
    """유니크 제약을 걸기 전에 기존 중복을 정리한다.

    base(develop)의 `validate_img_key`는 형식 검증만 하고 중복을 보지 않았다. 즉 이
    제약 이전의 dev 데이터에는 같은 `img_key`를 가진 행이 있을 수 있고, 한 쌍이라도
    있으면 `AddConstraint`가 `could not create unique index`로 죽는다. migrate 실패는
    배포 스크립트를 그 자리에서 멈춘다.

    가장 오래된 1건이 key를 유지하고 나머지는 `img_key=NULL`로 만든다.
      - S3 객체는 고아가 되지 않는다 — 남은 1건이 계속 참조한다
      - 잃는 것은 "그 문의에서 이미지를 볼 수 있다"뿐이고, 원래 그 이미지는 다른
        문의의 것이었다
      - 파기 시그널은 `img_key`가 없으면 아무것도 예약하지 않으므로 부작용이 없다
    되돌리기는 noop이다 — 어느 행이 어떤 key를 갖고 있었는지 복원할 근거가 없다.
    """
    Inquiry = apps.get_model("supports", "Inquiry")
    # values(...).annotate(...)가 GROUP BY를 만든다. values_list(flat=True) 뒤에
    # annotate를 붙이면 출력 열이 둘이 되어 flat=True와 충돌한다.
    duplicated = (
        Inquiry.objects.filter(img_key__isnull=False)
        .values("img_key")
        .annotate(n=models.Count("id"))
        .filter(n__gt=1)
        .values_list("img_key", flat=True)
    )
    for key in list(duplicated):
        keep = (
            Inquiry.objects.filter(img_key=key)
            .order_by("id")
            .values_list("id", flat=True)[:1]
        )
        cleared = (
            Inquiry.objects.filter(img_key=key)
            .exclude(id__in=list(keep))
            .update(img_key=None)
        )
        logger.warning(
            "[문의 첨부 중복 정리] uq_inquiry_img_key 적용 전 중복 제거 "
            f"key={key} 유지=1건 해제={cleared}건"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("supports", "0003_inquiry_inquiryanswer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 부분 유니크는 비-CONCURRENTLY `CREATE UNIQUE INDEX`로 나가 ShareLock으로
        # 쓰기를 막는다. 배포는 트래픽을 끊고 migrate하므로(deploy.yml) 정상 경로에서는
        # 대기가 없지만, 남아 있는 세션(psql·수동 exec) 하나가 잡고 있으면 무한정
        # 기다리며 그 뒤의 모든 쓰기가 줄선다. 5초에 끊고 실패시키면 배포 스크립트가
        # 구 스택을 되살린다 — 조용히 멈춰 있는 것보다 낫다.
        #
        # `SET LOCAL`이어야 한다. 비-LOCAL `SET`은 COMMIT 후에도 **세션에 남고**
        # `migrate`는 모든 마이그레이션을 한 커넥션으로 돌리므로, 이 뒤에 오는
        # users/0007(CHECK 추가 = AccessExclusiveLock + 전체 스캔)이나
        # users/0008(비-CONCURRENTLY GIN)까지 5초 제한을 물려받는다. 그쪽은 정당하게
        # 5초를 넘길 수 있어서, 여기서 정한 값이 남의 마이그레이션을 죽이면 안 된다.
        migrations.RunSQL(
            "SET LOCAL lock_timeout = '5s'", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.CreateModel(
            name="PendingInquiryAttachmentDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pending_inquiry_attachment_deletions",
                "ordering": ["created_at"],
            },
        ),
        migrations.RunPython(
            _null_out_duplicate_img_keys, migrations.RunPython.noop, elidable=True
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("img_key__isnull", False)),
                fields=("img_key",),
                name="uq_inquiry_img_key",
            ),
        ),
    ]
