# Generated by Django 6.0.5 on 2026-08-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supports", "0004_inquiry_ix_inquiry_img_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingAttachmentDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pending_attachment_deletions",
                "ordering": ["created_at"],
            },
        ),
    ]
