# Generated by Django 6.0.5 on 2026-06-01 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.utils.ulid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("address_name", models.CharField(max_length=255)),
                ("road_address_name", models.CharField(max_length=255)),
                ("place_name", models.CharField(max_length=255)),
                ("kakao_id", models.BigIntegerField()),
                ("x", models.DecimalField(decimal_places=14, max_digits=17)),
                ("y", models.DecimalField(decimal_places=14, max_digits=17)),
            ],
            options={
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True, default="")),
                ("thumbnail", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "posts",
            },
        ),
        migrations.CreateModel(
            name="PostSpot",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="post_spots",
                        to="posts.location",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spots",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "db_table": "post_spots",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PostSpotImage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("img_url", models.TextField()),
                ("original_image_url", models.TextField()),
                ("img_order", models.PositiveIntegerField()),
                (
                    "post_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="posts.postspot",
                    ),
                ),
            ],
            options={
                "db_table": "post_spot_images",
                "ordering": ["img_order"],
            },
        ),
    ]
