# Generated by Django 6.0.5 on 2026-06-02 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postspotimage",
            old_name="img_url",
            new_name="img_key",
        ),
        migrations.RenameField(
            model_name="postspotimage",
            old_name="original_image_url",
            new_name="original_img",
        ),
        migrations.RemoveField(
            model_name="location",
            name="kakao_id",
        ),
    ]
