# Generated by Django 6.0.5 on 2026-06-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_img_url_postspotimage_img_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="postspot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="postspotimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
