# Generated by Django 6.0.5 on 2026-06-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_postlike"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="description",
        ),
    ]
