# Generated by Django 6.0.5 on 2026-06-14 22:38
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_bookmark"),
    ]

    operations = [
        VectorExtension(),
        TrigramExtension(),
    ]
