# Generated by Django 6.0.5 on 2026-06-15 09:05

from django.db import migrations, models

import apps.posts.models.model


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_postrec_postclick"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="random_score",
            field=models.FloatField(
                db_index=True, default=apps.posts.models.model._get_random
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
