# Generated by Django 6.0.5 on 2026-06-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_post_comment_count_post_like_count_post_random_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="spot_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
