# Generated by Django 6.0.5 on 2026-06-19 06:53

from django.db import migrations
from django.db.models import Count


def backfill_spot_count(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    for post in Post.objects.annotate(real_count=Count("spots")):
        post.spot_count = post.real_count
        post.save(update_fields=["spot_count"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_add_spot_count_to_post"),
    ]

    operations = [
        migrations.RunPython(backfill_spot_count, migrations.RunPython.noop),
    ]
