# Generated by Django 6.0.5 on 2026-06-21 09:18

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models

import apps.core.utils.ulid


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_backfill_spot_count"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostRec",
            new_name="PostEmbedding",
        ),
    ]
