# Generated by Django 6.0.5 on 2026-06-21 09:35

import django.db.models.deletion
from django.db import migrations, models

import apps.core.utils.ulid


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_postrec_rename_postembedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postembedding",
            name="raw_embedding",
        ),
        migrations.CreateModel(
            name="PostCodeword",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codewords", models.JSONField(blank=True, default=dict)),
                ("codebook_version", models.CharField(max_length=16)),
                (
                    "embedding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clusters",
                        to="posts.postembedding",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("embedding", "codebook_version"),
                        name="uniq_embedding_version",
                    )
                ],
            },
        ),
    ]
