# Generated by Django 6.0.5 on 2026-06-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0015_copy_codewords_to_postcodeword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postembedding",
            name="codebook_version",
        ),
        migrations.RemoveField(
            model_name="postembedding",
            name="codewords",
        ),
    ]
