# Generated by Django 6.0.5 on 2026-07-07 05:22

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY 는 트랜잭션 밖에서만 실행 가능
    atomic = False

    dependencies = [
        ("posts", "0016_remove_postembedding_codebook_version_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "created_at"], name="bookmarks_user_id_2ce2db_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="postlike",
            index=models.Index(
                fields=["user", "created_at"], name="post_likes_user_id_eb9740_idx"
            ),
        ),
    ]
