# Generated by Django 6.0.5 on 2026-07-11 08:29

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("posts", "0017_bookmark_bookmarks_user_id_2ce2db_idx_and_more"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="location",
            index=models.Index(fields=["y", "x"], name="ix_locations_y_x"),
        ),
    ]
