# Generated by Django 6.0.5 on 2026-07-13 02:23

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY 는 트랜잭션 밖에서만 실행 가능
    atomic = False

    dependencies = [
        ("posts", "0018_location_ix_locations_y_x"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="location",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("address_name"),
                    name="gin_trgm_ops",
                ),
                name="loc_addr_trgm",
            ),
        ),
        AddIndexConcurrently(
            model_name="location",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("road_address_name"),
                    name="gin_trgm_ops",
                ),
                name="loc_road_addr_trgm",
            ),
        ),
        AddIndexConcurrently(
            model_name="location",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("place_name"),
                    name="gin_trgm_ops",
                ),
                name="loc_place_trgm",
            ),
        ),
    ]
