# Generated by Django 6.0.5 on 2026-07-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0019_location_loc_addr_trgm_location_loc_road_addr_trgm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="thumbnail_width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postspotimage",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postspotimage",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
