# Generated by Django 6.0.5 on 2026-07-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0020_post_thumbnail_height_post_thumbnail_width_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postspot",
            name="content",
            field=models.TextField(blank=True, default="", max_length=3000),
        ),
    ]
