# Generated by Django 6.0.5 on 2026-07-01 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["receiver", "target_id", "is_read"],
                name="ix_receiver_target_id_is_read",
            ),
        ),
    ]
