# Generated by Django 6.0.5 on 2026-07-07 04:06

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("notifications", "0002_notification_ix_receiver_target_id_is_read"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="notification",
            index=models.Index(fields=["created_at"], name="ix_notification_created_at"),
        ),
    ]
