# Generated by Django 6.0.5 on 2026-08-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_ix_notification_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("follow", "Follow"),
                    ("comment", "Comment"),
                    ("comment_like", "Comment Like"),
                    ("post_like", "Post Like"),
                    ("dm", "Dm"),
                    ("inquiry_answered", "Inquiry Answered"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("post", "Post"),
                    ("dm", "Dm"),
                    ("inquiry", "Inquiry"),
                ],
                max_length=20,
            ),
        ),
    ]
